version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: kolesa_postgres
    restart: always
    environment:
      DB_HOST: "localhost"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "kolesa"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
